version: '3.8'

networks:
  kiwi_networks:
    driver: bridge

services:
  kiwi_backend:
    container_name: kiwi_backend
    environment:
      - TZ=UTC
    build: 
      context: ../KiwiBackend
    ports:
      - "8080:8080"
    volumes:
      - ../KiwiBackend:/app
    networks:
      - kiwi_networks

  redis:
    container_name: redis_kiwi
    environment:
      - TZ=UTC
    build:
      context: ./redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/app
    networks:
      - kiwi_networks

  postgresql:
    container_name: kiwidb
    build: 
      context: ./postgresql
    ports:
      - "5432:5432"
    networks:
      - kiwi_networks
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456  
      - TZ=UTC
    

# docker compose -p kiwi_backend up -d