version: '3.8'

networks:
  kiwi_networks:
    driver: bridge

services:
  kiwi_backend:
    container_name: kiwi_backend
    build: 
      context: ../KiwiBackend
    ports:
      - "8080:8080"
    volumes:
      - ../KiwiBackend:/app
    networks:
      - kiwi_networks

  mysql:
    container_name: kiwidb
    build: 
      context: ./mysql
    ports:
      - "3306:3306"
    networks:
      - kiwi_networks
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    

# docker compose -p kiwi_backend up -d